### ISSUE TITLE
CollectionInputFilter throws exception on scalar input

### ISSUE THREAD

**Issue by autowp** [zendframework/zend-inputfilter#127]
```php
    public function testCollectionInputFilterMustNotThrowsExceptionOnScalar()
    {
        $inputFilterManager = $this->getApplicationServiceLocator()->get('InputFilterManager');
    
        $factory = new \Zend\InputFilter\Factory($inputFilterManager);
        $inputFilter = $factory->createInputFilter([
            'type' => \Zend\InputFilter\CollectionInputFilter::class,
        ]);
    
        $inputFilter->setData('asd'); // throws Zend\InputFilter\Exception\InvalidArgumentException: Zend\InputFilter\CollectionInputFilter::setData expects an array or Traversable collection; invalid collection of type string provided
    }
```

That breaks to use input-filter especially where used nested collection filters.

**Comment by weierophinney** [comment]
@autowp That's expected behavior. Collections _require_ that the incoming data is an array or traversable. If you're seeing that, it means the client-side code is submitting something that the input filter cannot deal with. As such, you have two options:

- If this is from a form-based submission, fix the markup to ensure the submitted values are structured correctly.
- If this is within an API, you can either let that bubble out, and have your error handler report a client-side error to the user, or manually wrap the `setData()` call in a try/catch block so you can report it yourself.

**Comment by autowp** [comment]
Ok. But that looks not symmetrical to scalar validations like StringLength where type isValid([]) never follow to Exception.

**Comment by weierophinney** [comment]
Validation is a separate subsystem, and independent from the input filters. Additionally, in this case, the exception happens before any validation is even attempted; it's thrown precisely because the value for would likely lead to serious errors further down the stack, including hydrators, filters, and validators.
