### ISSUE TITLE
Boolean Filter causes input to be required

### ISSUE THREAD

**Issue by jerv13** [zendframework/zend-inputfilter#9]
When configuring and Input like:

    [
        'name' => 'isSomeValue',
        'required' => false,
        'filters' => [
            ['name' => 'Zend\Filter\Boolean'],
        ],
    ];

\Zend\InputFilter\Input::isValid() method returns false.

It has something to do with the 'notEmptyValidator'.

If I change \Zend\InputFilter\Input line ~341 from:

        if (! $allowEmpty && ! $continueIfEmpty) {
            $this->injectNotEmptyValidator();
        }

To:

        if (! $allowEmpty && ! $continueIfEmpty && $required) {
            $this->injectNotEmptyValidator();
        }

It works as expected, but I am not sure of the impact.

**Comment by weierophinney** [comment]
Since some boolean values can be evaluated as empty (`0`, `false`, etc.), you also need to add the `allow_empty` and `continue_if_empty` flags to your input.

**Comment by jerv13** [comment]
If I set the value 'required' = false, doesn't that imply that I am ok with empty values?

**Comment by weierophinney** [comment]
@jerv13 Without the other two, it will not pass handling on to the validators when an empty value is detected. `continue_if_empty`, in particular, is the one you definitely need here, as it ensures the value is passed on to validators even if it fails an `empty()` check.

**Comment by jerv13** [comment]
I see, so this is to support multiple validation cases.  My case has no validators.

Just FYI, this change (as of ZF2 v2.3.9) caused a bunch of our existing Boolean filters to break, so it is worth noting.

Thanks for your help!

**Comment by jerv13** [comment]
I changed my config to:

    [
        'name' => 'isSomeValue',
        'required' => false,
        'allow_empty' => true,
        'continue_if_empty' => true,
        'filters' => [
            ['name' => 'Zend\Filter\Boolean'],
        ],
    ];

Works with issue.

**Comment by weierophinney** [comment]
@jerv13 I misinterpreted your intent, and thus gave some invalid advice earlier.

First, filters are run *prior* to validators. As such, your Boolean filter will run before validation, casting the value according to the rules you specify to the validator. If we assume you use the defaults, this means the value will be cast to an actual boolean value.

This means that during validation, you have a boolean value. If the key for the input is present in the data, it will attempt to validate it, according to the rules laid out in zendframework/zf2#7474 (which was introduced with 2.4 as well as the changes you noted above, and to clarify those changes properly; that PR contains a table showing all permutations of the `required`, `allow_empty`, and `continue_if_empty` flags). In particular, if the `required` flag is `false`, but a value is present, *validation still must be run*, which is why the other flags come into play.

Because you are expecting a boolean value, you should mark the value as `allow_empty`. This will ensure that it will not immediately invalidate the value when it evaluates to `false`. If you further use `continue_if_empty`, it will pass the value on to any validators you've defined; if you have no validators, you can omit the flag. Setting the `allow_empty` flag essentially allows you to short-circuit validation.

The changes in 2.4 forward were due to the fact that a number of issues around edge cases had been raised, and an audit of the code found that the intended paths were not covered adequately by tests, while simultaneously we had developers depending on behavior that we never intended.

**Comment by jerv13** [comment]
According to the permutation:

required === false + allow_empty === false + continue_if_empty === false -> validators are NOT run

**Comment by weierophinney** [comment]
@jerv13 It looks like you commented that one combination wasn't working, re-opened, and subsequently deleted the comment and closed it again. Do you still feel something needs to be fixed? Based on the deleted comment, there very likely could be, but I'm unsure if you discovered something else in the meantime.

**Comment by rvdlee-salesupply** [comment]
@weierophinney I've just had this same "issue". It seems a thing that remained in here because of loose  type checking in validation? I noticed that PHP 5.6 and 7.0 are required in the composer.json while both are EOL at this point.

I'm also using the Boolean filter in my specific case and works completely as expected. The validator however assumes false is an empty value due to lack of strict type checking?

I mean, at this point the filters are really mature and capable of filtering pretty much all types without problems, so value false shoudn't be an "empty" value. Also noticed that both options have been marked as deprecated. Is there something in the works to replace whilst not BC-breaking the code in this module? Love to hear your thoughts on this.

**Line 228 in Input.php**
```
    /**
     * @deprecated 2.4.8 Add Zend\Validator\NotEmpty validator to the ValidatorChain.
     *
     * @return bool
     */
    public function allowEmpty()
    {
        return $this->allowEmpty;
    }
```

**Line 246 in Input.php**
```
/**
     * @deprecated 2.4.8 Add Zend\Validator\NotEmpty validator to the ValidatorChain. Should always return `true`.
     *
     * @return bool
     */
    public function continueIfEmpty()
    {
        return $this->continueIfEmpty;
    }
```

**Line 429 in Input.php**
```
        // At this point, we need to run validators.
        // If we do not allow empty and the "continue if empty" flag are
        // BOTH false, we inject the "not empty" validator into the chain,
        // which adds that logic into the validation routine.
        if (! $allowEmpty && ! $continueIfEmpty) {
            $this->injectNotEmptyValidator();
        }
```
